FROM laravelphp/php-fpm:8.2

WORKDIR /var/www/html

COPY . .

RUN composer install --optimize-autoloader --no-dev
RUN php artisan key:generate

EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
